The test for bakefilize in the PATH broke on Windows due to space in the path name.  Handling it separately now.
FossilOrigin-Name: f36f98c1805b83282d8e1fa2925d17596b46cffeed4ea15dbfee52ed610dd1f5

diff --git a/bootstrap b/bootstrap
--- a/bootstrap
+++ b/bootstrap
@@ -70,12 +70,19 @@ then
 	echo
 	exit 1
 fi
+if [ ! -x "$bakefilize" ] && ! type -p "$bakefilize" > /dev/null
+then
+	echo
+	echo "Failed to find the bakefilize script.  Is Bakefile installed?"
+	echo
+	exit 1
+fi
 
 # Check for existence of needed tools, so we can give a better error
 # message than the shell will.
 tools="make"														# POSIX
 tools="$tools aclocal autoconf autoheader autoreconf libtoolize"	# Autotools
-tools="$tools bakefile $bakefilize bakefile_gen"					# Bakefile
+tools="$tools bakefile bakefile_gen"								# Bakefile
 for tool in $tools
 do
 	if ! type -p $tool > /dev/null
